rest:
  host: 192.168.4.65
  port: 80
  user: admin
  password: "12345678"

description:
  crit_adjust_kes: >
  crit_kes: >
    Критерию соответствуют скважины, для которых выполняются следующие условия:

    - скважина работает в постоянном режиме;

    - номинальная производильность ЭЦН не более 125;

    - высота столба жидкости над ЭЦН менее 400м;

    - дебит жидкости составляет менее 60% от номинала ЭЦН.
  crit_right: >
  crit_up: >
  crit_pritok: >
    Критерию соответствуют скважины, для которых выполняются следующие условия:

    - скважина работает в постоянном режиме;

    - номинальная производительность ЭЦН не менее 160;

    - высота столба жидкости над ЭЦН менее 400м;

    - дебит жидкости составляет менее 70% от номинала ЭЦН.

  crit_technology: >
  crit_const: >
  crit_shtuz: >